### ISSUE TITLE
Permissions error [Errno13]

### ISSUE THREAD

**Issue by tstoeger2** [AIDungeon/AIDungeon#103]
When I try to run the "python3 play.py" command, I get "PermissionError" [Errno13] Permission denied: 'generator/gpt2/models/model_v5/encoder.json'"

```
python3 play.py
(A bunch of "Future Warning"s)
AI Dungeon 2 will save and use your actions and game to continually improve AI
 Dungeon. If you would like to disable this enter 'nosaving' for any action.
 This will also turn off the ability to save games.

Initializing AI Dungeon! (This might take a few minutes)

Traceback (most recent call last):
  File "play.py", line 271, in <module>
    play_aidungeon_2()
  File "play.py", line 106, in play_aidungeon_2
    generator = GPT2Generator()
  File "/home/user/AIDungeon/generator/gpt2/gpt2_generator.py", line 31, in __init__
    self.enc = encoder.get_encoder(self.model_name, models_dir)
  File "/home/user/AIDungeon/generator/gpt2/src/encoder.py", line 124, in get_encoder
    with open(os.path.join(models_dir, model_name, "encoder.json"), "r") as f:
PermissionError: [Errno 13] Permission denied: 'generator/gpt2/models/model_v5/encoder.json'
```

How can I fix this?

**Comment by louisgv** [comment]
What's your environment? Also show me the output for:

```
ls -la /home/user/AIDungeon/generator/gpt2/models/model_v5
```
and
```
ls -l /home/user/AIDungeon/generator/gpt2/models/model_v5/encoder.json
```

**Comment by tstoeger2** [comment]
> What's your environment? Also show me the output for:
> 
> ```
> ls -la /home/user/AIDungeon/generator/gpt2/models/model_v5
> ```
> 
> and
> 
> ```
> ls -l /home/user/AIDungeon/generator/gpt2/models/model_v5/encoder.json
> ```

I'm working in WSL.  Here are the outputs:
`ls -ls /home/user/AIDungeon/generator/gpt2/models/model_v5
total 6099896
      0 ---------- 1 user user        355 Dec 10 14:40 checkpoint
   1020 ---x--x--x 1 user user    1042301 Dec 10 14:40 encoder.json
      0 ---------- 1 user user         91 Dec 10 14:40 hparams.json
6084420 ---------- 1 user user 6230444800 Dec 10 14:42 model-550.data-00000-of-00001
     24 ---------- 1 user user      20724 Dec 10 14:37 model-550.index
  13984 ---------- 1 user user   14316502 Dec 10 14:39 model-550.meta
    448 ---------- 1 user user     456318 Dec 10 14:38 vocab.bpe`

`ls -l /home/user/AIDungeon/generator/gpt2/models/model_v5/encoder.json
---x--x--x 1 user user 1042301 Dec 10 14:40 /home/user/AIDungeon/generator/gpt2/models/model_v5/encoder.json`

**Comment by louisgv** [comment]
@tstoeger2  If you know how to use WSL and linux in general, try changing the permission of the whole folder using chmod like so:

```
chmod -R 0755 /home/user/AIDungeon/generator/gpt2/models/model_v5
```

However, it's very likely that you will NOT be able to run it from WSL. 

WSL doesn't have bridging GPU driver support so you will not have enough resource to run the game at all:

https://github.com/Microsoft/WSL/issues/1788

**Comment by tstoeger2** [comment]
> @tstoeger2 If you know how to use WSL and linux in general, try changing the permission of the whole folder using chmod like so:
> 
> ```
> chmod -R 0755 /home/user/AIDungeon/generator/gpt2/models/model_v5
> ```
> 
> However, it's very likely that you will NOT be able to run it from WSL.
> 
> WSL doesn't have bridging GPU driver support so you will not have enough resource to run the game at all:
> 
> [microsoft/WSL#1788](https://github.com/microsoft/WSL/issues/1788)

Oh.  That's unfortunate.  How would you recommend running the game on Windows?

**Comment by louisgv** [comment]
@tstoeger2 do you have enough resource to run it? (12GB of RAM). If not, you should use Collab. If you do, follow this guide: http://familiarcycle.net/aidungeon-on-windows.html

And the reddit thread: https://www.reddit.com/r/AIDungeon/comments/e8fz8l/putting_together_a_frequently_asked_questions_list/
