### ISSUE TITLE
[BUG] How to avoid re-downloading model after timeout?

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [AIDungeon/AIDungeon#105]
Prior to the torrent solution for downloading the NN weights, if a session timed out, you could reconnect and "run all" (or simply select "restart and run all") and it would not have to re-download the model, displaying instead "model already installed". But now, using either method, it takes a long time to do that, because (I think) it's downloading the model again.

Am I wrong?

**Comment by louisgv** [comment]
I'm working on a solution for this that will allow you to backup the model into Google Drive, and then when it's time out, you can simply run another code block to copy the model back to the project. PR coming soon

**Comment by louisgv** [comment]
This can be closed with #110
