### ISSUE TITLE
[BUG] Error during game.

### ISSUE THREAD

**Issue by LJXLJXLJX** [AIDungeon/AIDungeon#109]
> Generating story...
> 
> 
> You are ljx, a knight living in the kingdom of Larion. You have a steel longsword
>  and a wooden shield. You are on a quest to defeat the evil dragon of Larion.
>  You've heard he lives up at the north of the kingdom. You set on the path to
>  defeat him and walk into a dark forest. As you enter the forest you see a large
>  black dragon flying over the trees. He looks down upon you as he flies overhead
> > 
> .
> 
> "Ah, another one of your kind". The dragon says. "I'm sure they're all like that".
> 
> The dragon turns his head slightly and sees you. His eyes narrow as he stares
>  at you
> 
> .
> > attack
> 
> You swing your sword at the dragon's face. It swings its tail at you, but you
>  dodge it by jumping over it. You then land on the dragon's back and begin to
>  stab with your sword.
>  
> > attack
> 
> You continue to stab the dragon. He lets out a roar and smashes his claw into
>  your chest. You fall off of him and roll away from the blow. You quickly get
>  up and try to run, but the dragon catches you again
> > hide in the wood
> 
> You crawl through the undergrowth. Suddenly, you hear a noise behind you. You
>  turn around and see a large group of orcs come out of the woods. They look angry
>  and ready for battle.
> > ask for help to kill the dragon
> 
> You stand up and raise your hands in surrender. The orcs stop their fighting
>  and stare at you. One orc raises his hand and points at you. He says:
> "This is our king! We want no more trouble!"
> > I am a knight, not a king.
> 
> You look down at yourself and say:
> "I don't know what you mean, but I'm not a king".
> > let them kill the dragon
> 
> You walk towards the dragon and start stabbing it repeatedly with your sword.
>  You keep attacking until you feel the dragon's life force drain away. You then
>  grab the dragon's body and throw it onto the ground.
> > eat the dragon
> 
> You pick up the dragon corpse and put it in your mouth. You chew on the dragon
>  for several minutes before swallowing it whole
> > Resurrect the dragon
> 
> You take the dragon's blood and pour some into your wounds. You immediately feel
>  better
> > find another dragon

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
>     return fn(*args)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
>     target_list, run_metadata)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
>     run_metadata)
> tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
>   (0) Resource exhausted: OOM when allocating tensor with shape[1,48,2,25,498,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
> 	 [[{{node sample_sequence/while/concat}}]]
> Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
> 
> 	 [[sample_sequence/while/Exit_3/_1387]]
> Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
> 
>   (1) Resource exhausted: OOM when allocating tensor with shape[1,48,2,25,498,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
> 	 [[{{node sample_sequence/while/concat}}]]
> Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
> 
> 0 successful operations.
> 0 derived errors ignored.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "play.py", line 271, in <module>
>     play_aidungeon_2()
>   File "play.py", line 234, in play_aidungeon_2
>     result = "\n" + story_manager.act(action)
>   File "/content/AIDungeon/story/story_manager.py", line 207, in act
>     result = self.generate_result(action_choice)
>   File "/content/AIDungeon/story/story_manager.py", line 212, in generate_result
>     block = self.generator.generate(self.story_context() + action)
>   File "/content/AIDungeon/generator/gpt2/gpt2_generator.py", line 119, in generate
>     text = self.generate_raw(prompt)
>   File "/content/AIDungeon/generator/gpt2/gpt2_generator.py", line 102, in generate_raw
>     self.context: [context_tokens for _ in range(self.batch_size)]
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 956, in run
>     run_metadata_ptr)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1180, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
>     run_metadata)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
>   (0) Resource exhausted: OOM when allocating tensor with shape[1,48,2,25,498,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
> 	 [[node sample_sequence/while/concat (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
> Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
> 
> 	 [[sample_sequence/while/Exit_3/_1387]]
> Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
> 
>   (1) Resource exhausted: OOM when allocating tensor with shape[1,48,2,25,498,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
> 	 [[node sample_sequence/while/concat (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
> Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
> 
> 0 successful operations.
> 0 derived errors ignored.
> 
> Original stack trace for 'sample_sequence/while/concat':
>   File "play.py", line 271, in <module>
>     play_aidungeon_2()
>   File "play.py", line 106, in play_aidungeon_2
>     generator = GPT2Generator()
>   File "/content/AIDungeon/generator/gpt2/gpt2_generator.py", line 51, in __init__
>     top_p=top_p,
>   File "/content/AIDungeon/generator/gpt2/src/sample.py", line 120, in sample_sequence
>     back_prop=False,
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/control_flow_ops.py", line 2753, in while_loop
>     return_same_structure)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/control_flow_ops.py", line 2245, in BuildLoop
>     pred, body, original_loop_vars, loop_vars, shape_invariants)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/control_flow_ops.py", line 2170, in _BuildLoop
>     body_result = body(*packed_vars_for_body)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/control_flow_ops.py", line 2705, in <lambda>
>     body = lambda i, lv: (i + 1, orig_body(*lv))
>   File "/content/AIDungeon/generator/gpt2/src/sample.py", line 98, in body
>     else tf.concat([past, next_outputs["presents"]], axis=-2),
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
>     return target(*args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/array_ops.py", line 1420, in concat
>     return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_array_ops.py", line 1257, in concat_v2
>     "ConcatV2", values=values, axis=axis, name=name)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
>     op_def=op_def)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
>     attrs, op_def, compute_device)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
>     op_def=op_def)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
>     self._traceback = tf_stack.extract_stack()
> 
> Game saved.
> To load the game, type 'load' and enter the following ID: 745e2362-1bbe-11ea-ada8-0242ac1c0002

**Comment by dyc3** [comment]
What are your specs?

**Comment by dalinarkholin** [comment]
Same Error here.

Processor: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz 4.20 GHz
Installed RAM: 16.0 GB
NVIDIA GeForce GTX 1060 6GB

Windows 10
Version 1903
OS build 18362.476

Using Chrome 78

I have a saved game(that I don't care about) that I can't seem to continue.
```
"Yeah, we won".
> who is the dead captain?
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[1,48,2,25,563,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node sample_sequence/while/concat}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[sample_sequence/while/Exit_3/_1387]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[1,48,2,25,563,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node sample_sequence/while/concat}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "play.py", line 271, in <module>
    play_aidungeon_2()
  File "play.py", line 234, in play_aidungeon_2
    result = "\n" + story_manager.act(action)
  File "/content/AIDungeon/story/story_manager.py", line 207, in act
    result = self.generate_result(action_choice)
  File "/content/AIDungeon/story/story_manager.py", line 212, in generate_result
    block = self.generator.generate(self.story_context() + action)
  File "/content/AIDungeon/generator/gpt2/gpt2_generator.py", line 119, in generate
    text = self.generate_raw(prompt)
  File "/content/AIDungeon/generator/gpt2/gpt2_generator.py", line 102, in generate_raw
    self.context: [context_tokens for _ in range(self.batch_size)]
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[1,48,2,25,563,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node sample_sequence/while/concat (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[sample_sequence/while/Exit_3/_1387]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[1,48,2,25,563,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node sample_sequence/while/concat (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.

Original stack trace for 'sample_sequence/while/concat':
  File "play.py", line 271, in <module>
    play_aidungeon_2()
  File "play.py", line 106, in play_aidungeon_2
    generator = GPT2Generator()
  File "/content/AIDungeon/generator/gpt2/gpt2_generator.py", line 51, in __init__
    top_p=top_p,
  File "/content/AIDungeon/generator/gpt2/src/sample.py", line 120, in sample_sequence
    back_prop=False,
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/control_flow_ops.py", line 2753, in while_loop
    return_same_structure)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/control_flow_ops.py", line 2245, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/control_flow_ops.py", line 2170, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/control_flow_ops.py", line 2705, in <lambda>
    body = lambda i, lv: (i + 1, orig_body(*lv))
  File "/content/AIDungeon/generator/gpt2/src/sample.py", line 98, in body
    else tf.concat([past, next_outputs["presents"]], axis=-2),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/array_ops.py", line 1420, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_array_ops.py", line 1257, in concat_v2
    "ConcatV2", values=values, axis=axis, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
```

**Comment by dyc3** [comment]
@dalinarkholin  Are you running it on your GPU or CPU? AI Dungeon 2 requires 12 GB of vram

**Comment by dalinarkholin** [comment]
Ah, yeah connected to GPU which only has 6 GB. that's likely it. Thanks

**Comment by louisgv** [comment]
This is the same out of memory problem as #156 , can be closed. The develop version of the notebook has an utility block that let you ask colab for more resource. 

FYI, 6GB is barely enough to hold the model itself 😆
