### ISSUE TITLE
[feat] Continue last save

### ISSUE THREAD

**Issue by jorgeer** [AIDungeon/AIDungeon#115]
Whether the game crashes, or you leave the game for another reason after saving, remembering which game you were playing the last time is pretty tedious. Looking at the modification time of the saved stories, it should be possible to add a "continue" option to the first menu, which resumes the most recent story.

**Comment by nickwalton** [comment]
This would require tracking user information which we currently don't do with the save games. We will definitely have that in the hosted app version, and we can maybe set that up for the open source system depending on if people want their user info stored with saved games
