### ISSUE TITLE
[BUG] Broken on Python 3.8.0?

### ISSUE THREAD

**Issue by kik4444** [AIDungeon/AIDungeon#123]
**Describe the bug**
After a big update to my system, the game refuses to start now with this error
```
play.py:161: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(story_manager.story.actions) is 0:
Traceback (most recent call last):
  File "play.py", line 2, in <module>
    from generator.gpt2.gpt2_generator import *
  File "/Fast-Games/AI Dungeon 2/generator/gpt2/gpt2_generator.py", line 5, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
```
I think it may be because python updated, now `python -V` returns `Python 3.8.0` as the version

**To Reproduce**
1. Attempt to start the script with `python play.py`

**Expected behavior**
It should start

**Additional context**
- OS - Linux Kiko-LM 5.4.2-1-MANJARO #1 SMP PREEMPT Thu Dec 5 09:55:57 UTC 2019 x86_64 GNU/Linux

**Comment by ben-bay** [comment]
Yeah, this is because tensorflow v1.15 only works up to python 3.6 :( 

You'll have to manually install python 3.6 for this to work.
