### ISSUE TITLE
[BUG] "Ask" as verb often causes the generator to run for a very long time

### ISSUE THREAD

**Issue by ryvenn** [AIDungeon/AIDungeon#131]
**Describe the bug**
Some verbs, like "ask," very frequently cause the generator to run forever without outputting text or giving control back to the user. This is frustrating because if you have to terminate the process in Windows (while running locally) it prevents the game from being saved.

**To Reproduce**
Steps to reproduce the behavior: Unfortunately I don't have a save on hand in a situation where this is guaranteed, but here is an example from earlier: "ask the little girl who all these people are" results in the infinite loop. Reloading (I remembered to make a manual save before trying "ask" that time) at the same point and trying "make the little girl tell you who all these people are" works fine, as expected.

The problem seems worse in long-running games. In case it is relevant, note that I have self.memory = 15 in story_manager.py because 20 was causing 1024 token crashes (see issue #68).

**Expected behavior**
Preferably it outputs something even if it's nonsense, or else it returns control to me and lets me input something else.

**Screenshots**

**Additional context**
- Windows 10, running on CPU (i7-7700HQ, 16GB RAM)
- self.memory = 15, removed the censor
- sometimes occurs with other verbs, but "ask" is such a frequent offender that I curse every time I forget and type it in

**Comment by ryvenn** [comment]
Perhaps it is not infinite but just really, really long - I left it running for about half an hour, and when I went back to it after typing this bug report it had finished. Typical commands take 1-2 minutes to resolve on my system and 3-4 I consider quite long, so for some reason "ask" may take 10 times longer.

**Comment by kik4444** [comment]
Running it locally on Linux here. Sometimes the same happens to me too, though I've never left it for long enough to see if it produces an output

**Comment by Arndress** [comment]
According to a user on 4chan:

> it tries to clear out "You ask/You say" lines from the last line in the response, but if it only has one line then it deletes all of it, and then generates another one (to presumably the same result, forever)

**thadunge2** reports to have fixed this error in his fork here: https://github.com/thadunge2/AIDungeon/commit/b996a0bc464846923c61005d0d0cee3739e0058f

**Comment by AZaitzeff** [comment]
I find that any time I type in dialog (even without say/ask) it runs for longer than my other commands.
