### ISSUE TITLE
Save locally when gsutils is not present

### ISSUE THREAD

**Issue by CoppaMan** [AIDungeon/AIDungeon#140]
Trying to save when gsutils is not installed crashes the application. Instead of crashing, the story could be stored locally and inform the user at the start that saves are not saved to a cloud. It might also helpful to add the gsutils dependency  to the readme #

**Comment by dyc3** [comment]
`gsutil` is listed in the requirements.txt file. You should have installed the dependencies with `pip install -r requirements.txt`
