### ISSUE TITLE
[BUG] Entering invalid save at the start causes a crash

### ISSUE THREAD

**Issue by kik4444** [AIDungeon/AIDungeon#142]
When you start the game you get to choose between loading a save or starting a new game. If you choose to load a save then enter an invalid argument, it crashes with this log
```
Traceback (most recent call last):
  File "play.py", line 271, in <module>
    play_aidungeon_2()
  File "play.py", line 188, in play_aidungeon_2
    result = story_manager.story.load_from_storage(load_ID)
AttributeError: 'NoneType' object has no attribute 'load_from_storage'
```

**Comment by ben-bay** [comment]
Great catch, I'll try to get to this soon.

**Comment by louisgv** [comment]
@ben-bay have you got to this? If not I think I can tackle it.

**Comment by ben-bay** [comment]
@louisgv I haven't yet, I'll take all the help I can get!
