### ISSUE TITLE
[BUG] install.sh not working on colab

### ISSUE THREAD

**Issue by louisgv** [AIDungeon/AIDungeon#145]
**Describe the bug**
The `install.sh` script does not seem to work properly on collab. It does not install the right dependency. It seems that the script will bail dependency installation on some check.

**To Reproduce**

Run install, copy model, then play game -> Game does not load due to missing dependency.

**Expected behavior**

`install.sh` should check if pip is available, and if it is, simply run that. 

**Additional context**
- Colab

I think this is a regression introduced by #143

**Comment by ben-bay** [comment]
Hey I think I got this working again by adding an install of `python3-venv`. Can you verify?

**Comment by ben-bay** [comment]
Looks like I just managed to stabilize `develop`. Lmk if new problems arise.
