### ISSUE TITLE
[BUG] can't delete printed text correctly. 

### ISSUE THREAD

**Issue by TimohaIsGod** [AIDungeon/AIDungeon#151]
- OS - win10
can't delete any text from the middle of printed text.

**Comment by dyc3** [comment]
Can you provide a few screenshots or a video to describe what's happening?

**Comment by TimohaIsGod** [comment]
sry. I described the wrong action
1) write random text
2) move the cursor to the middle of the text
3) type anything
= ???
![Screenshot_1](https://user-images.githubusercontent.com/18659544/70844773-d05d0800-1e56-11ea-9671-e971a3d46a58.png)
![Screenshot_2](https://user-images.githubusercontent.com/18659544/70844774-d05d0800-1e56-11ea-913b-42a90bb8c75d.png)
![Screenshot_3](https://user-images.githubusercontent.com/18659544/70844775-d05d0800-1e56-11ea-927c-c46df630aa6a.png)

**Comment by louisgv** [comment]
I think this is due to running the notebook off vscode which might have a bug with the nb input integration... Try just run the jnb server and open the notebook on your browser instead.

**Comment by TimohaIsGod** [comment]
i'm launch game from cmd and all is fine. thanks
