### ISSUE TITLE
[BUG] Commands not interpreted as commands

### ISSUE THREAD

**Issue by kik4444** [AIDungeon/AIDungeon#164]
In the latest version that I cloned from github in the last 15 minutes, commands are not interpreted as commands. For example "save" and "revert" and others are taken literally as instructions for my character.

**Comment by louisgv** [comment]
@kik4444 the way to issue command has changed. You will need to use a forward dash for command like so: `/save`

**Comment by kik4444** [comment]
You're right that was it. Thanks.
