### ISSUE TITLE
[BUG] Game crashes upon restarting story

### ISSUE THREAD

**Issue by Audixas** [AIDungeon/AIDungeon#172]
## 🐛 Bug Report

**Describe the bug**
Game crashes completely upon restarting a story by either ending it or using the /restart command.

**How to Reproduce**

1. Start a story as normal
2. Either end a game or use /restart so that it asks you to rate the story
3. Game crashes

**Expected behavior**
It is expected that the game would let you restart with a new story normally.

**Additional context**
- Develop branch
- Running on a local machine

**Comment by kik4444** [comment]
Does it also crash when you do /save

**Comment by snarfblam** [comment]
Happens consistently
```
Traceback (most recent call last):
  File "play.py", line 292, in <module>
    play_aidungeon_2()
  File "play.py", line 127, in play_aidungeon_2
    while story_manager.story is None: 
AttributeError: 'UnconstrainedStoryManager' object has no attribute 'story'
```

**Comment by marktaiwan** [comment]
It's due to
https://github.com/AIDungeon/AIDungeon/blob/f158fa08cdc8b381e0fd806d24dbc2151e65a1d8/play.py#L128-L129
deleting the `story` attribute, leading to the error when the loop immediately after tries to access it. Change it to something like `story_manager.story = None` should fix it.

**Comment by JushBJJ** [comment]
happens to me aswell
![image](https://user-images.githubusercontent.com/36951064/70864528-9d259080-1f9e-11ea-8b09-fd7c35004b29.png)

**Comment by Audixas** [comment]
Latest commits have fixed the issue, restarting now works as intended.
