### ISSUE TITLE
[BUG] /restart yields error

### ISSUE THREAD

**Issue by perstar** [AIDungeon/AIDungeon#175]
## 🐛 Bug Report

**Describe the bug**
`/revert` yields an error.
```
> /restart
Please rate the story quality from 1-10: 5
Game saved.
To load the game, type 'load' and enter the following ID: a18f350c-202c-11ea-a572-0242ac1c0002
Traceback (most recent call last):
  File "play.py", line 292, in <module>
    play_aidungeon_2()
  File "play.py", line 127, in play_aidungeon_2
    while story_manager.story is None: 
AttributeError: 'UnconstrainedStoryManager' object has no attribute 'story'
```

**How to Reproduce**

1. Run on colab (install; download model; play)
2. /restart

**Comment by ben-bay** [comment]
What branch is this bug occurring on?

**Comment by ben-bay** [comment]
Also, it is `/revert`, `/restart`, or both?

**Comment by perstar** [comment]
`\restart`. Sorry my mind was slipping while typing, but the cut-and-paste is true!

Regarding branch I'm just following the [official link](https://colab.research.google.com/github/nickwalton/AIDungeon/blob/master/AIDungeon_2.ipynb) to play the game. When doing it now again I see that it is using `--branch master`.

**Comment by kyz0n** [comment]
the game deletes the current story atribute, but doesn't initalizes it as a "None" again.

`while True:`
`        if story_manager.story != None:`
`               del story_manager.story`
`        while story_manager.story is None:`

find play.py in the game's folder and then add `story_manager.story=None` under `del story_manager.story` it's probably a handfisted fix, but it works

**Comment by ben-bay** [comment]
No idea how this slipped in, thanks for pointing it out.

**Comment by ben-bay** [comment]
Added this fix.
