### ISSUE TITLE
[BUG] Missing context for custom start

### ISSUE THREAD

**Issue by JWNoctis** [AIDungeon/AIDungeon#185]
## 🐛 Bug Report

**Describe the bug**
Currently, the game does not store any context string for custom start.

play.py:76

```python
if choice == len(settings):

        context = ""
        console_print(
            "\nEnter a prompt that describes who you are and the first couple sentences of where you start "
            "out ex:\n 'You are a knight in the kingdom of Larion. You are hunting the evil dragon who has been "
            + "terrorizing the kingdom. You enter the forest searching for the dragon and see' "
        )
        prompt = input("Starting Prompt: ")
        return context, prompt
```
This entire feature is also broken in the latest develop branch by mismatched return value. Presume it's being rewritten?

**Expected behavior**
Have the entire user provided prompt or something else relevant, rather than an empty string, saved as context and made available to the generator after enough actions or save/load.

**Additional context**
- local installation, latest develop branch with gsutil commented out and self.memory=16.

**Comment by Herohtar** [comment]
This shouldn't have been closed, as the fix in #186 only gets rid of the crash, but doesn't solve the issue of custom settings having no context, which is mentioned in the OP.
