### ISSUE TITLE
Trying to generate a 'custom' setting will result in a crash [BUG] 

### ISSUE THREAD

**Issue by Rippertear** [AIDungeon/AIDungeon#191]
## 🐛 Bug Report

I tried to make a custom setting, received an error message instead. I tried a few different things, including the recommended prompt ('You are a knight in the kingdom of Larion. You are hunting the evil dragon who has been terrorizing the kingdom. You enter the forest searching for the
 dragon and see'), all of which to the same response: 

"Traceback (most recent call last):
  File "play.py", line 359, in <module>
    play_aidungeon_2()
  File "play.py", line 178, in play_aidungeon_2
    setting_key, character_key, name, character, setting_description = select_game()
ValueError: not enough values to unpack (expected 5, got 2)"

**How to Reproduce**

Start a new game and attempt to input a custom setting.

**Expected behavior**
Expected to be able to input a custom setting without the game crashing.

**Additional context**
Using Google Chrome and the provided OOM fix, if that's relevant

**Comment by ben-bay** [comment]
Thanks, this bug was just recently fixed on both `develop` and `master`. Reply to this if you find otherwise.
