### ISSUE TITLE
[BUG] Quotes in the AI response sometimes prematurely trigger the end of the response.

### ISSUE THREAD

**Issue by bryanlyon** [AIDungeon/AIDungeon#200]
## 🐛 Bug Report

**Describe the bug**
Quotes in the AI response sometimes trigger the end of the response.

**How to Reproduce**

Play through with a lot of Dialog: say "blah blah blah".
This leads to responses with a lot of dialog, and situations where quotes cause the end of the AI response.

"She slaps you.  You say "

**Expected behavior**
The response should reach a reasonable and logical end, not stopping in the middle.

**Additional context**
- Colab or local machine?
Both
- `master` or `develop` branch?
Master
- (add any other context about the problem here)
This seems likely to be a training problem where the model was probably given clipped data in it's training where the quotes were stripped but it could be a parsing error where you're failing to parse the output correctly and are stripping important quotes and dialog.  The training issue seems more likely since this problem is not consistent, where sometimes the quotes actually are retained.

**Comment by snarfblam** [comment]
Looks like same issue as #90: [BUG] Dialog items not show.

**Comment by bryanlyon** [comment]
Agreed, closing for duplication with #90
