### ISSUE TITLE
[BUG] Pasting longer custom promts in mobile version is not possible

### ISSUE THREAD

**Issue by dragranis** [AIDungeon/AIDungeon#207]
## 🐛 Bug Report

**Describe the bug**
I have encountered this bug on android version. When I am writing custom prompt, the length doesn't matter and everything is fine. When i copy custom prompt from my notepad and try to paste it into the game, it is instantly removed from the input.

**How to Reproduce**

1. Try to paste longer text into custom prompt on android version ( I guess at least 50 words)

**Expected behavior**
Text is pasted and i could press "enter" to start generating a story

**Screenshots**

**Additional context**
- Mobile ( Android)

Sorry if i posted it in wrong section. I haven't found a repository dedicated for mobile version :P

**Comment by Renha** [comment]
Same on iOS version

**Comment by ben-bay** [comment]
Will forward this to the mobile people :)
