### ISSUE TITLE
[HELP] Can't seem to run install.sh.

### ISSUE THREAD

**Issue by Montydog9** [AIDungeon/AIDungeon#213]
It splooges out an error which says: ERROR: Could not find a version that satisfies the requirement tensorflow==1.15 (from -r C:/SSD Games/AIDungeon/requirements.txt (line 7)) (from versions: none)
ERROR: No matching distribution found for tensorflow==1.15 (from -r C:/SSD Games/AIDungeon/requirements.txt (line 7))

I've installed it but still get the error

**Comment by ben-bay** [comment]
This happens to me when I use the wrong version in Python, like python 3.8. Check your version?

**Comment by douchecanoe** [comment]
So this has some fun problems. The version of pip distributed with a bunch of OS's (Ubuntu 18.04 Bionic in my case) doesn't recognize tensorflow==1.15 as a valid version. So, update pip right? 

...Except upgrading pip breaks pip right now...https://github.com/pypa/pip/issues/5599

Only valid workaround for the breakage is to use an explicit call from python. 

So modifying the install script manually to `python -m pip3 install tensorflow==1.15`
