### ISSUE TITLE
TensorRT?

### ISSUE THREAD

**Issue by Akababa** [AIDungeon/AIDungeon#25]
I'm trying to get tensorRT working but I need the saved_model.pb file. Can you upload it?

**Comment by justinglibert** [comment]
+1 for that! We can do inference much better with a pb file :)

**Comment by Akababa** [comment]
@nickwalton any updates on getting the savedmodel.pb up for tinkering?

**Comment by nickwalton** [comment]
You should be able to load the model and save it as a savedmodel.pb. Can't you reconstruct it from the model?

**Comment by Akababa** [comment]
I tried a few different ways but couldn't get it to work for some reason. Do you happen to have a working code example or know the names of the variables to export?

One of the solutions I tried: https://blog.metaflow.fr/tensorflow-how-to-freeze-a-model-and-serve-it-with-a-python-api-d4f3596b3adc

**Comment by nickwalton** [comment]
Try something like this:


from generator.gpt2.gpt2_generator import *
generator = GPT2Generator()
model = generator.output

# Save the model to a .pb file
MODEL_DIR = "/content/Generator/saved"
version = 1
export_path = os.path.join(MODEL_DIR, str(version))
tf.saved_model.simple_save(generator.sess, export_path,
inputs={"context": generator.context}, outputs={"output":
generator.output})

**Comment by Akababa** [comment]
That worked! Beautiful, thanks
