### ISSUE TITLE
Unicode Decode Error when reading opening.txt

### ISSUE THREAD

**Issue by Rioghasarig** [AIDungeon/AIDungeon#31]
On the machine I'm using I get a UnicodeDecodeError when I read the opening.txt file. 

Traceback (most recent call last):
  File "play.py", line 211, in <module>
    play_aidungeon_2()
  File "play.py", line 79, in play_aidungeon_2
    starter = file.read()
  File "/global/software/sl-7.x86_64/modules/langs/python/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2: ordinal not in range(128)

Replacing the file with some ASCII text fixed it, though.

**Comment by Notloc** [comment]
Same issue for me. I'm on Windows 10.

Got past it like @Rioghasarig did.

**Comment by arbrog** [comment]
I also got this on ubuntu 18.04, replacing with ascii fixed it

**Comment by Akababa** [comment]
I fixed it by changing to this:

`
    with open('opening.txt', 'r', encoding="utf-8") as file:`

**Comment by Notloc** [comment]
I ended up needing that fix for all file operations throughout the repo, so thank you very much @Akababa

**Comment by ben-bay** [comment]
I'm assuming this has all been fixed..
