### ISSUE TITLE
Local installation isn't documented

### ISSUE THREAD

**Issue by palant** [AIDungeon/AIDungeon#48]
When running the game locally, the instructions are currently incorrect:

* Both instructions and `install.sh` assume that `python` and `pip` refer to Python 3. Usually that will be `python3` and `pip3` however.
* You need to run `sudo pip3 install gsutil` before you can run `install.sh`
* The `tensorflow` module is an additional requirement not listed in `requirements.txt`.

**Comment by aengl** [comment]
Also, should be `tensorflow==1.15` since version 2 won't work.

**Comment by palant** [comment]
Strange, pip installed tensorflow 1.14.0 for me yesterday. No idea why...

**Comment by nEOtechnican** [comment]
Let alone trying to install it on Windows 10, referring to a problem in grpcio ( https://github.com/grpc/grpc/issues/20831 ) you currently cannot install tensorflow after all using python 3.8.

Will try it with older versions and supply a full install for windows10 if needed.

**Comment by aklein13** [comment]
@nEOtechnican I just removed the termios related lines (import and 1 code line) and it works fine on Windows

**Comment by nEOtechnican** [comment]
> 
> 
> @nEOtechnican I just removed the termios related lines (import and 1 code line) and it works fine on Windows

already did and on to the next, lots of thanks.

**Comment by MrKrzYch00** [comment]
I will share how I made it work on Ubuntu 18 running from pendrive on my 12GB notebook:
- apt install python3-pip
- pip3 install -r requirements.txt
- cd generator/gpt2
- pip3 install -r requirements.txt
- pip3 install pyyaml
- pip3 install tensorflow==1.13.1
- cd ../..
(note that 1.12 as stated on the original GPT-2 won't work as it will throw an error on play.py)

Then to run it:
- python3 play.py

Seems to be working just fine in the terminal:
![image](https://user-images.githubusercontent.com/11292594/70391456-d0cc4d80-19d5-11ea-8168-abb651aeb0ac.png)

**Comment by JamesHutchison** [comment]
Could we just put this in a docker image? Would simplify a lot and I don't think there's any size limits?

**Comment by palant** [comment]
Not quite fixed - I listed three points in the issue description, and only the last one was addressed.

**Comment by nickwalton** [comment]
Would need to be an Nvidia docker image though to take advantage of cuda

**Comment by zaerl** [comment]
Creating a docker image from [tensorflow/tensorflow:latest-gpu-py3](https://hub.docker.com/r/tensorflow/tensorflow/tags?page=1&name=latest-gpu-py3) with embedded the `model_v5` folder is indeed very simple and also there is no limit to images size on docker hub. I can create a `Dockerfile` for you if you want.
