### ISSUE TITLE
Use of 'termios' package prevents Windows compatibility 

### ISSUE THREAD

**Issue by lanekelly** [AIDungeon/AIDungeon#59]
The 'termios' package is not supported on Windows:

https://docs.python.org/3/library/termios.html

https://github.com/AIDungeon/AIDungeon/blob/d7b77553d21a171268d4d59e822b2c1635875d26/play.py#L4

I haven't tried via Windows Subsystem for Linux, can someone chime in if they've gotten it working on there?

Removing the imports and tcflush lines allows me to play.

**Comment by JushBJJ** [comment]
https://github.com/AIDungeon/AIDungeon/pull/54

**Comment by ben-bay** [comment]
PR #62 has been merged.
