### ISSUE TITLE
How do I launch it?

### ISSUE THREAD

**Issue by MidSnake** [AIDungeon/AIDungeon#67]
I have no idea on how to start this, and I was directed by the creator to come here to ask how.

**Comment by ben-bay** [comment]
Can you be more specific? Currently, just following the directions on aidungeon.io should work to play it.

**Comment by MidSnake** [comment]
Uh...I downloaded it, and the folder is a bunch of JSON, Data, and Index files, I don't see a settings, or a runtime button.

**Comment by ben-bay** [comment]
@MidSnake have you tried the instructions in (README.md)?

**Comment by MidSnake** [comment]
git clone https://github.com/AIDungeon/AIDungeon/
cd AIDungeon
./install.sh
python play.py

Uh...I don't know what that means. I have zero idea what this means. I have them in a folder, but I don't know WHAT to do.

**Comment by ben-bay** [comment]
@MidSnake go to http://www.aidungeon.io/ and press play
