### ISSUE TITLE
[BUG] SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by tmyrick** [AIDungeon/AIDungeon#70]
**Describe the bug**
After running `python play.py`
```
% python play.py
Traceback (most recent call last):
  File "play.py", line 2, in <module>
    from generator.gpt2.gpt2_generator import *
  File "/Users/travismyrick/rando/AIDungeon/generator/gpt2/gpt2_generator.py", line 7, in <module>
    from generator.gpt2.src import sample, encoder, model
  File "/Users/travismyrick/rando/AIDungeon/generator/gpt2/src/sample.py", line 62
    def sample_sequence(*, hparams, length, start_token=None, batch_size=None, context=None, temperature=1, top_k=0, top_p=1):
                         ^
SyntaxError: invalid syntax
```

**To Reproduce**
1. git clone
2. install
3. run it - get the error

**Expected behavior**
For the program to load properly without a syntax error?

**Screenshots**

**Additional context**
- osx catalina

**Comment by ben-bay** [comment]
What's your python version?

**Comment by GatoCreador887** [comment]
That looks the same as what happened to me when I tried to use python 2.7.

**Comment by ben-bay** [comment]
I'll add a note tothe README that it only supports python 3.

**Comment by cluzier** [comment]
> That looks the same as what happened to me when I tried to use python 2.7.
> Try using `python3 play.py`

Doesn't work, the version was meant for python2, not python3.
