### ISSUE TITLE
From someone who is somewhat tech illiterate

### ISSUE THREAD

**Issue by kborb** [AIDungeon/AIDungeon#71]
How do I open this up to play? I downloaded an app that recognizes the Python files, but all it does is open for not even a second before closing itself. I've tried this multiple times, and even checked to make sure it wasn't just running in the background, but nothing has come up.

**Comment by ben-bay** [comment]
Hey if all you want to do is play the game, go to http://www.aidungeon.io/ and click play.

**Comment by 3941** [comment]
@kborb 
Even then it's not so obvious at all. I thought I was just looking at a readme file, not the actual program.

The "How to play" section actually refers to the page you're on when you open:
https://colab.research.google.com/github/nickwalton/AIDungeon/blob/master/AIDungeon_2.ipynb

You wanna use the menus at the top of that page, like described.
