### ISSUE TITLE
Discord, torrent availablity

### ISSUE THREAD

**Issue by IIPoliII** [AIDungeon/AIDungeon#77]
Hey,

So I just saw a post on Reddit for sharing AiDungeon via torrents due to your high cost.

Firstly make the torrent available here it's surely the easiest please c:.
Secondly you could or host your website on an ipfs page so you will never have surcharge or I can help you hosting it with the 10 gb/s node that I used for sharing the torrent too c:.

And open a discord ! C: I maybe didn't saw it too but I am sure it will be really useful for everyone ! Thanks for this project ^^

**Comment by geoah** [comment]
There is a torrent for v5 posted a couple of days ago on https://github.com/AIDungeon/AIDungeon/issues/41#issuecomment-562937063

**Comment by WAUthethird** [comment]
Here's a Discord I just created: https://discord.gg/Dg8Vcz6

Currently a WIP.

**Comment by ben-bay** [comment]
> Here's a Discord I just created: https://discord.gg/Dg8Vcz6
> 
> Currently a WIP.

@WAUthethird can I add this to the README ?

**Comment by WAUthethird** [comment]
> > Here's a Discord I just created: https://discord.gg/Dg8Vcz6
> > Currently a WIP.
> 
> @WAUthethird can I add this to the README ?

Sure!

**Comment by IIPoliII** [comment]
> 
> 
> There is a torrent for v5 posted a couple of days ago on [#41 (comment)](https://github.com/AIDungeon/AIDungeon/issues/41#issuecomment-562937063)

I saw it on reddit but maybe we should put it in the readme thanks for the discord and the other things ^^

**Comment by ZerxXxes** [comment]
I also run an IPFS-node with 10Gbit/s internet connection and a public gateway, I would gladly pin the content to help provide bandwith to the gamefiles

**Comment by ben-bay** [comment]
Added discord to the README :)

**Comment by ben-bay** [comment]
Closing because 2/3 of this issue are resolved... feel free to open a new IPFS issue.
