### ISSUE TITLE
[BUG] Notebook Loading Issue

### ISSUE THREAD

**Issue by Inglonias** [AIDungeon/AIDungeon#82]
**Describe the bug**
Colab fails to load the notebook. Looks like a syntax error.

**To Reproduce**
Try to load via Colab

**Expected behavior**

**Screenshots**
![Screenshot_20191209-212137](https://user-images.githubusercontent.com/2125926/70489594-37cb2e80-1aca-11ea-8b13-a83daa98e218.png)

**Additional context**
- OS, environment
- Game settings
- Add any other context about the problem here.

**Comment by bdice** [comment]
Duplicate of #79.

**Comment by Inglonias** [comment]
Closed by PR #81
