### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Nick-AI-Generator** [AIDungeon/AIDungeon#96]
When ever i try to run it it show me this message
(copied from the AI Dungeon)

Traceback (most recent call last):
  File "play.py", line 271, in <module>
    play_aidungeon_2()
  File "play.py", line 106, in play_aidungeon_2
    generator = GPT2Generator()
  File "/content/AIDungeon/generator/gpt2/gpt2_generator.py", line 31, in __init__
    self.enc = encoder.get_encoder(self.model_name, models_dir)
  File "/content/AIDungeon/generator/gpt2/src/encoder.py", line 124, in get_encoder
    with open(os.path.join(models_dir, model_name, "encoder.json"), "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'generator/gpt2/models/model_v5/encoder.json'

and then it dosn't run if I'm doing something wrong please contact me at Kngihtemerald6@gmail.com

please i love this game and i need i back up and running soon
Thank you for your time

P.S it worked earlier today

**Comment by spencerhakim** [comment]
Pretty sure this URL needs to be updated. https://github.com/AIDungeon/AIDungeon/blob/master/install.sh#L8

**Comment by snglth** [comment]
Why not just to embed a magnet link into install.sh? I tried to do so in my fork (https://github.com/snglth/AIDungeon) and it works pretty well.

**Comment by Nick-AI-Generator** [comment]
The thingnis i dont know how im new to coding and i just found this game i
dont know how to do anything like that

**Comment by Akmp40** [comment]
@Nick-AI-Generator You can copy and paste the line of code seen above in @spencerhakim comment before running AiDungeon.
![image](https://user-images.githubusercontent.com/11835224/70607488-d2c52500-1bfe-11ea-8b02-a2b61244f036.png)

**Comment by Nick-AI-Generator** [comment]
Okay thank I got it now thanks alot

**Comment by louisgv** [comment]
Should be closed with #93
