### ISSUE TITLE
No Save Game on Quit for Loaded Games

### ISSUE THREAD

**Issue by hexive** [AIDungeon/AIDungeon#97]
```
From help:
"quit"     Quits the game and saves
```

Game saves on "quit" for new stories as expected. 
If you load a game and "quit" then no save is generated.

**Comment by dyc3** [comment]
I can reproduce this issue

**Comment by louisgv** [comment]
This is a problem. It seems when a story is loaded, it should be assigned a new ID to be saved into a new file. Or that there should be 2 saving option, default save to the same file, and another "Save new" to save to a new hash.

**Comment by dyc3** [comment]
I've seen people using save files to share custom prompts, so it should definitely be with a new id

**Comment by louisgv** [comment]
I know the code path where this is so I can take a whack at it. Hopefully can get a PR out by end of week.

**Comment by louisgv** [comment]
Investigation notes: It seems the main issue here is that the quit command prompts for the scoring of the story. The score of the story is being used to check whether the story should be saved or not.
